# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  image_resizer:
    class: AppBundle\Services\ImageResizer
  test_listener:
    class: AppBundle\Listener\TestListener
    tags:
      - { name: kernel.event_listener, method: yo, event: kernel.request }
    arguments: ["@doctrine"]
  custom_listener:
      class: AppBundle\Listener\CustomListener
      tags:
        - { name: kernel.event_listener, method: customHandler, event: custom.test_event }